
POST  http://localhost:4000/api/users/create-user
Content-Type: application/json

{
  "name": "Eleomar",
  "lastName": "Apellido paterno",
  "motherLastName": "Apellido materno"
}

### Errors

POST  http://localhost:4000/api/users/create-user
Content-Type: application/json

{
  "lastName": "Apellido paterno",
  "motherLastName": "Apellido materno",
  "phone": "9581231231",
  "email": "correoelectronico@ejemplo.com",
  "userName": "usuario",
  "password": "contraseña"
}

###

POST  http://localhost:4000/api/users/create-user
Content-Type: application/json

{
  "name": "aa",
  "lastName": "Apellido paterno",
  "motherLastName": "Apellido materno",
  "phone": "9581231231",
  "email": "correoelectronico@ejemplo.com",
  "userName": "usuario",
  "password": "contraseña"
}
