DELETE http://localhost:4000/api/users/delete/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjgzY2I0YWM3YWY5NGJiODYwNzIxYSIsInVzZXIiOiJ1c3VhcmlvIiwiaWF0IjoxNjIyNjk5NTE2fQ.e6Fv1krXZPlDAjV4SsUs--EvmhtcwxoK42rZGNQZG1Y