PUT http://localhost:4000/api/users/edit/60b2b57ff94d0c4028913e06
Content-Type: application/json

{
  "name": "Nombre",
  "lastName": "Apellido paterno",
  "motherLastName": "Apellido materno",
  "phone": "9581231231",
  "email": "correoelectronico@ejemplo.com",
  "userName": "usuario",
  "password": "contraseña"
}

### error

PUT http://localhost:4000/api/users/edit/60b2b57ff94d0c4028913e06
Content-Type: application/json

{
  "lastName": "Apellido paterno",
  "motherLastName": "Apellido materno",
  "phone": "9581231231",
  "email": "correoelectronico@ejemplo.com",
  "userName": "usuario",
  "password": "contraseña"
}