PUT http://localhost:4000/api/users/edit-password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjg3MjE4ZTdiOGYwM2FhODgzZDcyZSIsInVzZXIiOiJ1c3VhcmlvIiwiaWF0IjoxNjIyNzA1NDE1fQ.N6buwNU1NNT0EZW_oS4Yb7Cryhsy6qmw1jbW7hCx9cA

{
  "oldPassword": "contraseña1",
  "newPassword": "contraseña"
}